/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ngmanager

// Project response model
type ProjectResponse struct {
	Project *Project `json:"project,omitempty"`
	// Creation timestamp for the project
	Created int64 `json:"created,omitempty"`
	// Updated timestamp for the project
	Updated int64 `json:"updated,omitempty"`
}
