/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ngmanager

// This is the SSH key authentication details defined in Harness.
type SshKeyPathSpec struct {
	// This specifies the type of secret
	Type_ string `json:"type"`
	// SSH port
	Port int32 `json:"port,omitempty"`
	// SSH username
	Username string `json:"username"`
	// Path of the key file
	KeyPath string `json:"key_path"`
	// This is the passphrase provided while creating the SSH key for local encryption
	EncryptedPassphrase string `json:"encrypted_passphrase,omitempty"`
}
