/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ngmanager

type Secret struct {
	// Secret name
	Name string `json:"name"`
	// Secret slug
	Slug string `json:"slug"`
	// Organization slug for secret
	Org string `json:"org,omitempty"`
	// Project slug for secret
	Project string `json:"project,omitempty"`
	// Secret tags
	Tags map[string]string `json:"tags,omitempty"`
	// Secret description
	Description string      `json:"description,omitempty"`
	Spec        *SecretSpec `json:"spec"`
}
