/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the Access Control Service. This is under active development. Beware of the breaking change with respect to the generated code stub.
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// Resource Group response body
type ResourceGroupsResponse struct {
	// Resource Group Identifier
	Slug string `json:"slug"`
	// Resource Group Name
	Name string `json:"name"`
	// Color associated with the Resource Group.
	Color string `json:"color,omitempty"`
	// Resource Group tags
	Tags map[string]string `json:"tags,omitempty"`
	// Resource Group description
	Description string `json:"description,omitempty"`
	// Allowed scope levels for this Resource Group.
	AllowedScopeLevels []string `json:"allowed_scope_levels,omitempty"`
	// Included scopes for the resources belonging to the Resource Group.
	IncludedScope []ResourceGroupScope `json:"included_scope,omitempty"`
	// Specifies the actual resources present in the Resource Group.
	ResourceFilter []ResourceFilter `json:"resource_filter,omitempty"`
	// Boolean value for including all resources in Resource Group.
	IncludeAllResources bool `json:"include_all_resources,omitempty"`
	// This indicates if this Resource Group is managed by Harness or not. If true, Harness can manage and modify this Resource Group.
	HarnessManaged bool `json:"harness_managed,omitempty"`
	// Creation timestamp for Resource Group.
	Created int64 `json:"created,omitempty"`
	// Last modification timestamp for Resource Group.
	Updated int64 `json:"updated,omitempty"`
}
