/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the Access Control Service. This is under active development. Beware of the breaking change with respect to the generated code stub.
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// Filter request body for Resource Groups.
type ResourceGroupFilterRequestBody struct {
	// Filter by Account identifier.
	Account string `json:"account,omitempty"`
	// Filter by Organization identifier.
	Org string `json:"org,omitempty"`
	// Filter by Project identifier.
	Project string `json:"project,omitempty"`
	// Filter Resource Group matching by identifier/name.
	SearchTerm string `json:"search_term,omitempty"`
	// Filter by Resource Group identifiers
	IdentifierFilter []string `json:"identifier_filter,omitempty"`
	// Filter based on whether it has a particular Resource.
	ResourceSelectorFilter []ResourceSelectorFilter `json:"resource_selector_filter,omitempty"`
	// Filter based on whether the Resource Group is Harness Managed.
	ManagedFilter string `json:"managed_filter,omitempty"`
}
