/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the Access Control Service. This is under active development. Beware of the breaking change with respect to the generated code stub.
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// This contains details of the artifactory connector with encrypted username/password
type ArtifactoryEncryptedConnectorSpec struct {
	// This specifies the type of connector
	Type_ string `json:"type"`
	// artifactory repo url
	Url string `json:"url"`
	// Reference to encrypted Harness secret for artifactory username
	UsernameRef string `json:"username_ref"`
	// Reference to encrypted Harness secret for artifactory password
	PasswordRef string `json:"password_ref"`
	// List of unique delegate selectors
	DelegateSelectors []string `json:"delegate_selectors,omitempty"`
	// execute on delegate
	ExecuteOnDelegate bool `json:"execute_on_delegate,omitempty"`
}
