/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the Access Control Service. This is under active development. Beware of the breaking change with respect to the generated code stub.
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// Environment Request Body 
type EnvironmentRequest struct {
	// Identifier of the Environment
	Slug string `json:"slug"`
	// Name of the Environment
	Name string `json:"name"`
	// Description of the entity
	Description string `json:"description,omitempty"`
	// Environment tags
	Tags map[string]string `json:"tags,omitempty"`
	// YAML for the Environment Request
	Yaml string `json:"yaml"`
	// Color of the Environment
	Color string `json:"color,omitempty"`
	// Specify the environment type whether production or Preproduction.
	Type_ string `json:"type"`
}
