/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the Access Control Service. This is under active development. Beware of the breaking change with respect to the generated code stub.
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// Role Response Model
type RolesResponse struct {
	// Role Identifier
	Slug string `json:"slug"`
	// Role Name
	Name string `json:"name"`
	// Permissions for this Role.
	Permissions []string `json:"permissions,omitempty"`
	// The Scope levels at which this Role can be used.
	AllowedScopeLevels []string `json:"allowed_scope_levels,omitempty"`
	// Role description
	Description string `json:"description,omitempty"`
	// Role tags
	Tags map[string]string `json:"tags,omitempty"`
	Scope *RoleScope `json:"scope,omitempty"`
	// Creation timestamp for Role.
	Created int64 `json:"created,omitempty"`
	// Last modification timestamp for Role.
	Updated int64 `json:"updated,omitempty"`
	// This indicates if this Role is managed by Harness or not. If true, Harness can manage and modify this Role.
	HarnessManaged bool `json:"harness_managed,omitempty"`
}
