/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the Access Control Service. This is under active development. Beware of the breaking change with respect to the generated code stub.
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// Git Experience related details of the Entity.
type EntityGitDetails struct {
	// Entity identifier
	ObjectId string `json:"object_id,omitempty"`
	// Name of the branch.
	BranchName string `json:"branch_name,omitempty"`
	// File path of the Entity in the repository.
	FilePath string `json:"file_path,omitempty"`
	// Name of the repository.
	RepoName string `json:"repo_name,omitempty"`
	// Latest commit identifier.
	CommitId string `json:"commit_id,omitempty"`
	// File URL of the Entity.
	FileUrl string `json:"file_url,omitempty"`
	// Repository URL of the Entity.
	RepoUrl string `json:"repo_url,omitempty"`
}
