/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the Access Control Service. This is under active development. Beware of the breaking change with respect to the generated code stub.
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// Role request body
type CreateRoleRequest struct {
	// Role identifier
	Slug string `json:"slug"`
	// Role name
	Name string `json:"name"`
	// List of the permission identifiers.
	Permissions []string `json:"permissions,omitempty"`
	// Role description
	Description string `json:"description,omitempty"`
	// Role tags
	Tags map[string]string `json:"tags,omitempty"`
}
