/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the Access Control Service. This is under active development. Beware of the breaking change with respect to the generated code stub.
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// Scope of the Role
type RoleScope struct {
	// Account identifier
	Account string `json:"account,omitempty"`
	// Organization identifier
	Org string `json:"org,omitempty"`
	// Project identifier
	Project string `json:"project,omitempty"`
}
