/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the Access Control Service. This is under active development. Beware of the breaking change with respect to the generated code stub.
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// This has details of the connectivity status of the Connector.
type ConnectorConnectivityDetail struct {
	// Connectivity status of a Connector
	Status string `json:"status,omitempty"`
	// List of errors and their details
	Errors []ConnectorTestConnectionErrorDetail `json:"errors,omitempty"`
	// Summary of errors
	ErrorSummary string `json:"error_summary,omitempty"`
	// Time at which Test Connection was completed
	TestedAt int64 `json:"tested_at,omitempty"`
	// This is the last time at which the Connector was successfully connected
	ConnectedAt int64 `json:"connected_at,omitempty"`
}
