/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the Access Control Service. This is under active development. Beware of the breaking change with respect to the generated code stub.
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// This is the SSH key authentication details defined in Harness.
type WinRmTgtPasswordSpec struct {
	// This specifies the type of secret
	Type_ string `json:"type"`
	// WinRm port
	Port int32 `json:"port,omitempty"`
	// Kerberos principal
	Principal string `json:"principal,omitempty"`
	// Kerberos realm
	Realm string `json:"realm,omitempty"`
	// Kerberos password
	Password string `json:"password,omitempty"`
	// This is the Kerberos either to use SSL/https
	UseSsl bool `json:"use_ssl,omitempty"`
	// This is the Kerberos either to skip certificate checks
	SkipCertChecks bool `json:"skip_cert_checks,omitempty"`
	// This is the Kerberos powershell runs without loading profile
	UseNoProfile bool `json:"use_no_profile,omitempty"`
}
