/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// This is the SSH key authentication details defined in Harness.
type SshKerberosTgtPasswordSpec struct {
	// This specifies the type of secret
	Type_ string `json:"type"`
	// SSH port
	Port int32 `json:"port,omitempty"`
	// Kerberos principal
	Principal string `json:"principal,omitempty"`
	// Kerberos realm
	Realm string `json:"realm,omitempty"`
	// Kerberos password
	Password string `json:"password,omitempty"`
}
