/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Entity Details with its yaml validation result 
type EntityDetails struct {
	IsValid bool `json:"is_valid,omitempty"`
	ErrorMetadata *ErrorMetadata `json:"error_metadata,omitempty"`
	EntityMetadata *EntityMetadata `json:"entity_metadata,omitempty"`
	Identifier string `json:"identifier,omitempty"`
	Org string `json:"org,omitempty"`
	Project string `json:"project,omitempty"`
	EntityType string `json:"entity_type,omitempty"`
	EntityUrl string `json:"entity_url,omitempty"`
	Branch string `json:"branch,omitempty"`
}
