/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreditOverUsage struct {
	// Total number of overuse credits
	OverUsageCount int32 `json:"overUsageCount"`
	// Module Type for which the credits' overusage is being captured
	ModuleType string `json:"moduleType"`
}
