/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// This is the Infrastructure entity defined in Harness
type Infrastructure struct {
	// Account Identifier
	Account string `json:"account,omitempty"`
	// Identifier of the Environment Request.
	Identifier string `json:"identifier"`
	// Organization Identifier for the Entity.
	Org string `json:"org,omitempty"`
	// Project Identifier for the Entity.
	Project string `json:"project,omitempty"`
	// Name of the Infrastructure.
	Name string `json:"name"`
	// Name of the parent Environment.
	Environment string `json:"environment,omitempty"`
	Type_ *InfrastructureType `json:"type"`
	// Description of the entity
	Description string `json:"description,omitempty"`
	// Infrastructure tags
	Tags map[string]string `json:"tags,omitempty"`
	// version of harness yaml
	HarnessVersion string `json:"harness_version,omitempty"`
	// Yaml related to infrastructure
	Yaml string `json:"yaml,omitempty"`
}
