/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Organization response Model
type OrganizationResponse struct {
	Org *Organization `json:"org,omitempty"`
	// Creation timestamp for organization
	Created int64 `json:"created,omitempty"`
	// Updated timestamp for organization
	Updated int64 `json:"updated,omitempty"`
	// This indicates if this organization is managed by Harness or not. If true, Harness can manage and modify this organization.
	HarnessManaged bool `json:"harness_managed,omitempty"`
}
