/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LinkSsoGroupRequestDto struct {
	SsoId string `json:"sso_id,omitempty"`
	SsoGroupId string `json:"sso_group_id,omitempty"`
	SsoGroupName string `json:"sso_group_name,omitempty"`
}
