/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Secret response model
type SecretResponse struct {
	Secret *Secret `json:"secret,omitempty"`
	// Creation timestamp for the secret
	Created int64 `json:"created,omitempty"`
	// Updated timestamp for the secret
	Updated int64 `json:"updated,omitempty"`
	Draft bool `json:"draft,omitempty"`
	// Governance metadata information
	GovernanceMetadata *interface{} `json:"governance_metadata,omitempty"`
}
