/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CertificateDetailsDto struct {
	IssuedTo *CertificateIssuanceInfo `json:"issued_to,omitempty"`
	IssuedBy *CertificateIssuanceInfo `json:"issued_by,omitempty"`
	ValidFrom int64 `json:"valid_from,omitempty"`
	ValidTo int64 `json:"valid_to,omitempty"`
	SignatureAlgo string `json:"signature_algo,omitempty"`
}
