/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Response model of single release details
type ReleaseDetailsResponse struct {
	Id *interface{} `json:"_id,omitempty"`
	Account string `json:"account,omitempty"`
	Org string `json:"org,omitempty"`
	Project string `json:"project,omitempty"`
	ReleaseKey string `json:"release_key,omitempty"`
	ServiceDetails *ReleaseServiceDetails `json:"service_details,omitempty"`
	EnvironmentDetails *ReleaseEnvDetails `json:"environment_details,omitempty"`
}
