/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Response of signing an End User License Agreement
type EulaSignResponse struct {
	Signed bool `json:"signed,omitempty"`
	// Signing an End User License Agreement result
	Message string `json:"message,omitempty"`
}
