/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for NextGen Manager. This is under active development. Beware of the breaking change with respect to the generated code stub
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Response model of environment release details
type ReleaseEnvDetails struct {
	EnvId string `json:"env_id,omitempty"`
	EnvName string `json:"env_name,omitempty"`
	Org string `json:"org,omitempty"`
	Project string `json:"project,omitempty"`
	ConnectorRef string `json:"connector_ref,omitempty"`
	InfraName string `json:"infra_name,omitempty"`
	InfraId string `json:"infra_id,omitempty"`
	InfrastructureKind string `json:"infrastructure_kind,omitempty"`
}
